# Generated by Django 2.0rc1 on 2017-11-21 19:20

from django.db import migrations, models
import django.db.models.deletion
import sn_dispatcher.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default=sn_dispatcher.tools.generate_motion_sn, max_length=16, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='辩题名称')),
                ('title_zheng', models.CharField(max_length=100, verbose_name='正方持方')),
                ('title_fan', models.CharField(max_length=100, verbose_name='反方持方')),
                ('description', models.TextField(verbose_name='题解')),
                ('comment', models.TextField(verbose_name='备注')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_motion',
            },
        ),
        migrations.CreateModel(
            name='TeamMotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='motions.Motion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motions', to='team_management.Team')),
            ],
            options={
                'db_table': 'cms_team_motion',
            },
        ),
    ]
