# Generated by Django 2.0rc1 on 2017-11-21 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sn_dispatcher.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default=sn_dispatcher.tools.generate_member_sn, max_length=16, unique=True)),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('nickname', models.CharField(max_length=10, verbose_name='昵称')),
                ('school', models.CharField(max_length=30, verbose_name='学校')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cms_member',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default=sn_dispatcher.tools.generate_team_sn, max_length=16, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='队伍名称')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'cms_team',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='team_management.Member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='team_management.Team')),
            ],
            options={
                'db_table': 'cms_team_member',
            },
        ),
    ]
