# Generated by Django 2.0rc1 on 2017-11-21 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SNPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.CharField(editable=False, max_length=16, unique=True)),
                ('random_string', models.CharField(editable=False, max_length=13, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'TEAM'), (1, 'MEMBER'), (2, 'MOTION')])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cms_sn_pool',
            },
        ),
    ]
